num = set()

one = int(input("Enter the No.1: "))
num.add(one)
one = int(input("Enter the No.2: "))
num.add(one)
one = int(input("Enter the No.3: "))
num.add(one)
one = int(input("Enter the No.4: "))
num.add(one)
one = int(input("Enter the No.5: "))
num.add(one)
one = int(input("Enter the No.6: "))
num.add(one)
one = int(input("Enter the No.7: "))
num.add(one)
one = int(input("Enter the No.8: "))
num.add(one)

print(num)